#!/usr/bin/env bash

echo "== create bucket =="

#Check for bucket name
if [ -z "$1" ]; then 
    echo "A bucket name must be provided."
    exit 1
fi

BUCKET_NAME=$1
aws s3api create-bucket \
 --bucket $BUCKET_NAME \
 --create-bucket-configuration="LocationConstraint=eu-north-1" \
 --query Location \
 --output text