#!/usr/bin/env bash

echo "===delete bucket==="


#Check for bucket name
if [ -z "$1" ]; then 
    echo "A bucket name must be provided."
    exit 1
fi

BUCKET_NAME=$1
aws s3api delete-bucket \
 --bucket $BUCKET_NAME