#!/usr/bin/env bash

echo "===sync==="

set -e

#Check for bucket name
if [ -z "$1" ]; then 
    echo "A bucket name must be provided."
    exit 1
fi
#Check for filename prefix
if [ -z "$2" ]; then 
    echo "A file name prefix must be provided."
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where output files will be stored
OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove folder if it already exists
rm -r $OUTPUT_DIR

mkdir -p $OUTPUT_DIR

# generate random number to 
# determine the number of files to create
NUM_FILES=$((RANDOM % 6 + 5))

for((i = 1; i <= $NUM_FILES; i++)); do 
    RANDOM_FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    dd if=/dev/urandom of="$RANDOM_FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME
