#!/usr/bin/env bash

echo "===deploy s3 bucket via CFN==="

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--stack-name ${STACK_NAME} \
--region eu-central-1 \
--no-execute-changeset